# Sample .travis.yml for R projects

language: r

matrix:
  include:
  - r: release
    os: osx
  - r: release
    os: linux
    after_success: travis_wait Rscript -e 'covr::codecov()'
  - r: devel
    os: linux

sudo: false
cache: packages
warnings_are_errors: true
r_check_args: "--no-manual --timings"

env:
 global:
   - NOT_CRAN: true
   - _R_CHECK_FORCE_SUGGESTS_: false

notifications:
  email:
    on_success: change
    on_failure: change
