# Sample .travis.yml for R projects

language: r

matrix:
  include:
  - r: release
    os: osx
    brew_packages: libgit2
  - r: release
    os: linux
#    after_success: travis_wait 40 Rscript -e 'covr::codecov()'
  - r: devel
    os: linux

sudo: false
cache: packages
warnings_are_errors: true
r_check_args: "--no-manual --timings"

env:
 global:
   - BIGSNPR_CRAN: false
   - _R_CHECK_FORCE_SUGGESTS_: false
   - _R_CHECK_LENGTH_1_CONDITION_: verbose
   - _R_CHECK_LENGTH_1_LOGIC2_: verbose

notifications:
  email:
    on_success: change
    on_failure: change
